name: Construir y Publicar Imágenes Docker

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # --- TRABAJO 1: BACKEND ---
  build-and-push-backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      # Novedad: Configurar el motor avanzado de Docker
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraer metadatos para Docker (Tags y Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend

      - name: Construir y Subir Imagen de Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Novedad: Caché para acelerar builds en Go
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # --- TRABAJO 2: FRONTEND ---
  build-and-push-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      # Novedad: Configurar el motor avanzado de Docker
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraer metadatos para Docker (Tags y Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend

      - name: Construir y Subir Imagen de Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Novedad: Caché para acelerar dependencias de React/Node
          cache-from: type=gha
          cache-to: type=gha,mode=max